"""
Extension Function Registry

This file provides a centralized registry for all extension functions.
It maps extension names and function names to their actual implementations.

Auto-generated by the realms CLI extension command.
DO NOT EDIT MANUALLY - your changes will be overwritten.
"""

from typing import Callable, Optional
from kybra_simple_logging import get_logger

logger = get_logger("extension_packages.registry")

import extension_packages.voting.entry as voting_entry
import extension_packages.passport_verification.entry as passport_verification_entry
import extension_packages.llm_chat.entry as llm_chat_entry
import extension_packages.notifications.entry as notifications_entry
import extension_packages.erd_explorer.entry as erd_explorer_entry
import extension_packages.justice_litigation.entry as justice_litigation_entry
import extension_packages.vault.entry as vault_entry
import extension_packages.test_bench.entry as test_bench_entry
import extension_packages.member_dashboard.entry as member_dashboard_entry
import extension_packages.land_registry.entry as land_registry_entry
import extension_packages.admin_dashboard.entry as admin_dashboard_entry


def get_func(extension_name: str, function_name: str) -> Optional[Callable]:
    """
    Get a function from an extension by name.
    
    Args:
        extension_name: The ID of the extension
        function_name: The name of the function to retrieve
        
    Returns:
        The function object if found, None otherwise
    """
    logger.debug(f"Looking up function '{function_name}' in extension '{extension_name}'")
    
    # Map extension names to their entry modules
    extension_modules = {
        "voting": voting_entry,
        "passport_verification": passport_verification_entry,
        "llm_chat": llm_chat_entry,
        "notifications": notifications_entry,
        "erd_explorer": erd_explorer_entry,
        "justice_litigation": justice_litigation_entry,
        "vault": vault_entry,
        "test_bench": test_bench_entry,
        "member_dashboard": member_dashboard_entry,
        "land_registry": land_registry_entry,
        "admin_dashboard": admin_dashboard_entry,
    }
    
    # Get the extension module
    module = extension_modules.get(extension_name)
    if not module:
        logger.error(f"Extension '{extension_name}' not found in registry")
        raise ValueError(f"Extension '{extension_name}' not found")
    
    # Get the function from the module
    if not hasattr(module, function_name):
        logger.error(f"Function '{function_name}' not found in extension '{extension_name}'")
        raise AttributeError(f"Extension '{extension_name}' has no function '{function_name}'")
    
    func = getattr(module, function_name)
    logger.debug(f"Found function '{function_name}' in extension '{extension_name}'")
    return func
