name: 2. Run Tests (extensions)

on:
  workflow_run:
    branches: ['**']
    except:
      - main
    workflows: ["1. Build Docker Image (branch)"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: "${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'push' && !contains(github.event.head_commit.message, 'Bump version')) }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get commit SHA
        uses: actions/github-script@v6
        id: get-commit-sha
        with:
          script: |
            if (context.payload.workflow_run) {
              // Triggered by workflow_run event
              const workflow_run = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id
              });
              return workflow_run.data.head_sha;
            } else {
              // Triggered by push event
              return context.sha;
            }
      
      - name: Run extension tests
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }}
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }} bash -c "./tests/test_extensions.py"
