name: Publish

on:
  release:
    types: [created]
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    # Only run if the workflow_run event was successful or if it's a release or manual dispatch
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Verify version consistency
      run: |
        # Extract version from pyproject.toml
        PYPROJECT_VERSION=$(grep -Po '(?<=version = ")[^"]*' cli/pyproject.toml)
        # Extract version from __init__.py
        INIT_VERSION=$(grep -Po '(?<=__version__ = ")[^"]*' cli/realms_cli/__init__.py)
        
        echo "Version in pyproject.toml: $PYPROJECT_VERSION"
        echo "Version in __init__.py: $INIT_VERSION"
        
        # Make sure versions match
        if [ "$PYPROJECT_VERSION" != "$INIT_VERSION" ]; then
          echo "ERROR: Version mismatch between pyproject.toml ($PYPROJECT_VERSION) and __init__.py ($INIT_VERSION)"
          exit 1
        fi
      
    - name: Build package
      run: |
        cd cli
        python -m build
      
    - name: Check package
      run: |
        cd cli
        twine check dist/*
      
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd cli
        twine upload dist/*
