name: 2. Run Tests (Branch)

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Wait for Docker image to be available
        run: |
          # Wait up to 5 minutes for the Docker image to be available
          for i in {1..30}; do
            if docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }}; then
              echo "Docker image is available"
              break
            else
              echo "Waiting for Docker image... (attempt $i/30)"
              sleep 10
            fi
          done
      
      - name: Run linting checks
        run: |
          # First fix formatting issues
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }} ./scripts/run_linters.sh --fix
          # Then verify all issues are fixed
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }} ./scripts/run_linters.sh
      
      - name: Run frontend tests
        run: |
          # Run frontend tests
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }} bash -c "cd src/realm_frontend && npm test"
