name: 2. Run Tests Extensions (Branch)

on:
  workflow_run:
    workflows: ["1. Build Docker Image (branch)"]
    types:
      - completed

jobs:
  test-extensions:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch != 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Wait for Docker image to be available
        run: |
          # Wait up to 5 minutes for the Docker image to be available
          for i in {1..30}; do
            if docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ github.event.workflow_run.head_sha }}; then
              echo "Docker image is available"
              break
            else
              echo "Waiting for Docker image... (attempt $i/30)"
              sleep 10
            fi
          done
      
      - name: Run extension tests
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ github.event.workflow_run.head_sha }} bash -c "./tests/test_extensions.py"
