name: 2. Run Tests

on:
  workflow_run:
    workflows: ["1. Build Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get commit SHA from previous workflow
        uses: actions/github-script@v6
        id: get-commit-sha
        with:
          script: |
            const workflow_run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            return workflow_run.data.head_sha;
      
      - name: Run linting checks
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }}
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }} ./scripts/run_linters.sh
      
      # - name: Run tests in container
      #   run: |
      #     docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }}
      #     # TODO: replace this with your actual test commands
      #     docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }} echo "Running tests..."; exit 0
