name: 2. Run Tests

on:
  workflow_run:
    workflows: ["1. Build Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: "${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'push' && !contains(github.event.head_commit.message, 'Bump version')) }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get commit SHA
        uses: actions/github-script@v6
        id: get-commit-sha
        with:
          script: |
            if (context.payload.workflow_run) {
              // Triggered by workflow_run event
              const workflow_run = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id
              });
              return workflow_run.data.head_sha;
            } else {
              // Triggered by push or pull_request event
              return context.sha;
            }
      
      - name: Run linting checks
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }}
          # First fix formatting issues
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }} ./scripts/run_linters.sh --fix
          # Then verify all issues are fixed
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }} ./scripts/run_linters.sh
      
      - name: Run tests in container
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }}
          # Run frontend tests
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ steps.get-commit-sha.outputs.result }} bash -c "cd src/realm_frontend && npm test"
