name: 2. Run Tests Extensions (Main)

on:
  push:
    branches: [main]

jobs:
  test-extensions:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Wait for Docker image to be available
        run: |
          # Wait up to 5 minutes for the Docker image to be available
          for i in {1..30}; do
            if docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }}; then
              echo "Docker image is available"
              break
            else
              echo "Waiting for Docker image... (attempt $i/30)"
              sleep 10
            fi
          done
      
      - name: Run extension tests
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }} bash -c "./tests/test_extensions.py"
