name: 3. Deploy to Staging

on:
  workflow_run:
    workflows: ["2. Run Tests (Main)", "2. Run Tests Extensions (Main)"]
    types:
      - completed
    branches: [main]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Wait for both test workflows to complete
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const head_sha = '${{ github.event.workflow_run.head_sha }}';
            
            // Get all workflow runs for this commit
            const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              head_sha,
              status: 'completed'
            });
            
            // Check if both test workflows have completed successfully
            const testWorkflow = runs.workflow_runs.find(run => 
              run.name === '2. Run Tests (Main)' && run.conclusion === 'success'
            );
            const testExtensionsWorkflow = runs.workflow_runs.find(run => 
              run.name === '2. Run Tests Extensions (Main)' && run.conclusion === 'success'
            );
            
            if (!testWorkflow || !testExtensionsWorkflow) {
              core.setFailed('Both test workflows must complete successfully before deployment');
            }
      
      - name: Deploy to staging
        run: |
          # Store identity in a temporary file
          echo "${{ secrets.IC_IDENTITY_PEM }}" > identity.pem
          chmod 600 identity.pem
          
          # Pull the image that was tested
          docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ github.event.workflow_run.head_sha }}
          
          # Run deployment script with staging network
          docker run --rm \
            -v "$(pwd)/identity.pem:/app/identity.pem" \
            -v "$(pwd)/scripts/deploy_ic.sh:/app/deploy_ic.sh" \
            -v "$(pwd)/scripts/setup_demo.sh:/app/setup_demo.sh" \
            -e DFX_WARNING="-mainnet_plaintext_identity" \
            ghcr.io/${{ github.repository_owner }}/realms:${{ github.event.workflow_run.head_sha }} \
            bash -c "/app/deploy_ic.sh /app/identity.pem staging && /app/setup_demo.sh /app/identity.pem staging"
          
          # Clean up
          rm identity.pem
