name: 4. Create Release

on:
  workflow_dispatch:  # Allows manual triggering only
    inputs:
      release_type:
        description: 'Type of release (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      create_github_release:
        description: 'Create GitHub Release'
        required: false
        default: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PAT_GITHUB }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpversion semver
      
      # Bump version
      - name: Bump version
        id: bump_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create version file if it doesn't exist
          if [ ! -f "version.txt" ]; then
            echo "0.1.0" > version.txt
          fi
          
          # Calculate new version with Python
          CURRENT_VERSION=$(cat version.txt)
          NEW_VERSION=$(python -c "import semver; v=semver.VersionInfo.parse('${CURRENT_VERSION}'); print(v.bump_${{ github.event.inputs.release_type }}())")
          
          # Update version file
          echo "${NEW_VERSION}" > version.txt
          
          # Store new version for later use
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_OUTPUT
      
      # Pull and tag the base Docker image
      - name: Pull and tag Docker image
        run: |
          # Pull the base Docker image (without extensions)
          docker pull ghcr.io/${{ github.repository_owner }}/realms:latest
          
          # Tag with version number
          docker tag ghcr.io/${{ github.repository_owner }}/realms:latest \
            ghcr.io/${{ github.repository_owner }}/realms:v${{ steps.bump_version.outputs.NEW_VERSION }}
          
          # Push the versioned tag
          docker push ghcr.io/${{ github.repository_owner }}/realms:v${{ steps.bump_version.outputs.NEW_VERSION }}
      
      - name: Extract canister artifacts
        run: |
          # Create directory to ensure it exists for mounting
          mkdir -p artifacts

          # Build canisters in the Docker container and extract artifacts
          docker run --rm \
            -v "$(pwd)/artifacts:/artifacts" \
            ghcr.io/${{ github.repository_owner }}/realms:latest \
            bash -c "dfx start --background --clean && \
                    dfx canister create --all && \
                    dfx build --all && \
                    cp .dfx/local/canisters/realm_backend/realm_backend.wasm.gz /artifacts/ && \
                    cp .dfx/local/canisters/realm_backend/service.did /artifacts/realm_backend.did && \
                    cp .dfx/local/canisters/realm_registry_backend/realm_registry_backend.wasm.gz /artifacts/ && \
                    cp .dfx/local/canisters/realm_registry_backend/service.did /artifacts/realm_registry_backend.did && \
                    dfx stop"
          
          # Move artifacts to the root directory for the release
          mv artifacts/realm_backend.wasm.gz ./
          mv artifacts/realm_backend.did ./
          mv artifacts/realm_registry_backend.wasm.gz ./
          mv artifacts/realm_registry_backend.did ./
      
      # Push changes
      - name: Push changes
        run: |
          git add version.txt
          git commit -m "Bump version to $(cat version.txt)"
          git tag -a "v$(cat version.txt)" -m "Release v$(cat version.txt)"
          git remote set-url origin https://${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git
          git push origin
          git push origin --tags
      
      # Create a GitHub release
      - name: Create Release
        if: ${{ github.event.inputs.create_github_release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.NEW_VERSION }}
          name: Release v${{ steps.bump_version.outputs.NEW_VERSION }}
          generate_release_notes: true
          files: |
            realm_backend.wasm.gz
            realm_backend.did
            realm_registry_backend.wasm.gz
            realm_registry_backend.did
          body: |
            # Release v${{ steps.bump_version.outputs.NEW_VERSION }}
            
            This release includes:
            
            ## 📦 Release Assets
            
            ### 🐳 Docker Image (Base - No Extensions)
            ```bash
            docker pull ghcr.io/${{ github.repository_owner }}/realms:v${{ steps.bump_version.outputs.NEW_VERSION }}
            # or use :latest for the most recent release
            docker pull ghcr.io/${{ github.repository_owner }}/realms:latest
            ```
            
            ### 🔧 Canister Artifacts (WASM + DID)
            - `realm_backend.wasm.gz` + `realm_backend.did` - Main backend canister
            - `realm_registry_backend.wasm.gz` + `realm_registry_backend.did` - Registry backend canister
            
            ### 📁 Source Code
            - Source code (zip)
            - Source code (tar.gz)
            
            ## Installation
            
            **Deploy Canisters:**
            ```bash
            # Download the .wasm.gz and .did files
            dfx deploy --network ic
            ```
            
            **Run Docker Image:**
            ```bash
            docker run -it ghcr.io/${{ github.repository_owner }}/realms:v${{ steps.bump_version.outputs.NEW_VERSION }}
            ```
            
            ## Commit
            ${{ github.sha }}
