name: 4. Create Release

on:
  workflow_dispatch:  # Allows manual triggering only
    inputs:
      release_type:
        description: 'Type of release (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      create_github_release:
        description: 'Create GitHub Release'
        required: false
        default: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PAT_GITHUB }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpversion semver
      
      # Bump version
      - name: Bump version
        id: bump_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create version file if it doesn't exist
          if [ ! -f "version.txt" ]; then
            echo "0.1.0" > version.txt
          fi
          
          # Calculate new version with Python
          CURRENT_VERSION=$(cat version.txt)
          NEW_VERSION=$(python -c "import semver; v=semver.VersionInfo.parse('${CURRENT_VERSION}'); print(v.bump_${{ github.event.inputs.release_type }}())")
          
          # Update version file
          echo "${NEW_VERSION}" > version.txt
          
          # Store new version for later use
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_OUTPUT
      
      # Pull the latest Docker image
      - name: Pull Docker image
        run: |
          # Pull the Docker image that was already built in the build stage
          docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }}
      
      - name: Extract canister artifacts
        run: |
          # Create directory to ensure it exists for mounting
          mkdir -p artifacts

          # Extract artifacts from the known path in the Docker container
          docker run --rm \
            -v "$(pwd)/artifacts:/artifacts" \
            ghcr.io/${{ github.repository_owner }}/realms:${{ github.sha }} \
            bash -c "cp /app/.dfx/local/canisters/realm_backend/realm_backend.wasm.gz /artifacts/ && \
                    cp /app/.dfx/local/canisters/realm_backend/service.did /artifacts/realm_backend.did"
          
          # Move artifacts to the root directory for the release
          mv artifacts/realm_backend.wasm.gz ./
          mv artifacts/realm_backend.did ./
      
      # Push changes
      - name: Push changes
        run: |
          git add version.txt
          git commit -m "Bump version to $(cat version.txt)"
          git tag -a "v$(cat version.txt)" -m "Release v$(cat version.txt)"
          git remote set-url origin https://${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git
          git push origin
          git push origin --tags
      
      # Create a GitHub release
      - name: Create Release
        if: ${{ github.event.inputs.create_github_release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.NEW_VERSION }}
          name: Release v${{ steps.bump_version.outputs.NEW_VERSION }}
          generate_release_notes: true
          files: |
            realm_backend.wasm.gz
            realm_backend.did
          body: |
            # Release v${{ steps.bump_version.outputs.NEW_VERSION }}
            
            This release contains the compiled WASM and Candid (DID) files for the Internet Computer canisters.
            
            ## Included Canisters
            - realm_backend
            
            ## Installation
            Download the appropriate files and deploy using `dfx deploy` or your preferred deployment method.
            
            ## Commit
            ${{ github.sha }}
