name: 99. Force Deploy (main)

on:
  workflow_dispatch:
    inputs:
      canister:
        description: 'Canister to deploy (leave empty for all)'
        required: false
        default: ''
      commit:
        description: 'Commit SHA to deploy (leave empty for latest main)'
        required: false
        default: ''

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit || github.sha }}

      - name: Set deployment commit
        id: commit
        run: |
          DEPLOY_COMMIT="${{ github.event.inputs.commit || github.sha }}"
          echo "deploy_commit=$DEPLOY_COMMIT" >> $GITHUB_OUTPUT
          echo "Deploying commit: $DEPLOY_COMMIT"

      - name: Insert commit hash and datetime
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          sed -i "s/COMMIT_HASH_PLACEHOLDER/$COMMIT_HASH/g" src/realm_backend/api/status.py
          sed -i "s/COMMIT_HASH_PLACEHOLDER/$COMMIT_HASH/g" src/realm_frontend/src/app.html

          COMMIT_DATETIME=$(git log --format="%cd" --date=iso8601 -1)
          sed -i "s/COMMIT_DATETIME_PLACEHOLDER/$COMMIT_DATETIME/g" src/realm_frontend/src/app.html

          VERSION=$(cat version.txt)
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/g" src/realm_backend/api/status.py
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/g" src/realm_frontend/src/app.html

      - name: Deploy to staging
        run: |
          # Store identity in a temporary file
          echo "${{ secrets.IC_IDENTITY_PEM }}" > identity.pem
          chmod 600 identity.pem
          
          # Pull the image that was built (NOTE: we assume it was built in a previous workflow!)
          docker pull ghcr.io/${{ github.repository_owner }}/realms:${{ steps.commit.outputs.deploy_commit }}
          
          # Deploy using realms CLI with staging network
          # Mount the current workspace to use updated source files with commit metadata
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            -v "$(pwd)/identity.pem:/app/identity.pem" \
            -e DFX_WARNING="-mainnet_plaintext_identity" \
            ghcr.io/${{ github.repository_owner }}/realms:${{ steps.commit.outputs.deploy_commit }} \
            bash -c "realms create --random --network staging --deploy && realms deploy --network staging --identity /app/identity.pem"
          
          # Clean up
          rm identity.pem
