name: Force Deploy (main)

on:
  workflow_dispatch:
    inputs:
      canister:
        description: 'Canister to deploy (leave empty for all)'
        required: false
        default: ''
      commit:
        description: 'Commit SHA to deploy (leave empty for latest main)'
        required: false
        default: ''

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit || github.sha }}

      - name: Set deployment commit
        id: commit
        run: |
          DEPLOY_COMMIT="${{ github.event.inputs.commit || github.sha }}"
          echo "deploy_commit=$DEPLOY_COMMIT" >> $GITHUB_OUTPUT
          echo "Deploying commit: $DEPLOY_COMMIT"

      - name: Deploy to staging
        run: |
          # Store identity in a temporary file
          echo "${{ secrets.IC_IDENTITY_PEM }}" > identity.pem
          chmod 600 identity.pem
          
          # Pull the demo image (includes extensions)
          docker pull ghcr.io/${{ github.repository_owner }}/realms:demo-${{ steps.commit.outputs.deploy_commit }}
          
          # Deploy using realms CLI with staging network
          docker run --rm \
            -v "$(pwd)/identity.pem:/app/identity.pem" \
            -v "$(pwd)/deploy-logs:/app/deploy-logs" \
            -e DFX_WARNING="-mainnet_plaintext_identity" \
            ghcr.io/${{ github.repository_owner }}/realms:demo-${{ steps.commit.outputs.deploy_commit }} \
            bash -c "(dfx identity import my-identity /app/identity.pem --storage-mode=plaintext --force && \
                     dfx identity use my-identity && \
                     realms create --random --network staging --deploy); \
                     EXIT_CODE=\$?; \
                     mkdir -p /app/deploy-logs && \
                     cp -f dfx.log /app/deploy-logs/ 2>/dev/null || true && \
                     cp -f dfx2.log /app/deploy-logs/ 2>/dev/null || true && \
                     cp -f realms_cli.log /app/deploy-logs/ 2>/dev/null || true; \
                     exit \$EXIT_CODE"
          
          # Clean up
          rm identity.pem
      
      - name: Upload deployment logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: force-deploy-logs
          path: deploy-logs/
          retention-days: 7
