name: Deploy to Internet Computer

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      canister:
        description: 'Specific canister to deploy (leave empty to deploy all)'
        required: false
        type: 'string'

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          ./scripts/build_image.sh

      - name: Deploy to staging
        run: |
          # Store identity in a temporary file
          echo "${{ secrets.IC_IDENTITY_PEM }}" > identity.pem
          chmod 600 identity.pem
          
          # Set environment variables - always use staging for GitHub Actions
          CANISTER="${{ github.event.inputs.canister }}"
          
          # Run deployment in container
          docker run --rm \
            -v "$(pwd)/identity.pem:/app/identity.pem" \
            -e DFX_WARNING="-mainnet_plaintext_identity" \
            smart-social-contracts/realms:latest \
            bash -c "dfx identity import --force --storage-mode plaintext github-actions identity.pem && \
              dfx identity use github-actions && \
              npm install --legacy-peer-deps && \
              dfx deploy realm_backend --network ic && \
              dfx generate realm_backend && \
              npm run prebuild --workspace realm_frontend && \
              npm run build --workspace realm_frontend && \
              dfx deploy --network ic && \
              python /app/scripts/verify_deployment.py --network ic"

          # Clean up the temporary file
          rm identity.pem