name: Deploy to Internet Computer

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      canister:
        description: 'Specific canister to deploy (leave empty to deploy all)'
        required: false
        type: 'string'

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Insert commit hash
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          sed -i "s/COMMIT_HASH_PLACEHOLDER/$COMMIT_HASH/g" src/realm_backend/api/status.py
          sed -i "s/COMMIT_HASH_PLACEHOLDER/$COMMIT_HASH/g" src/realm_frontend/src/app.html
      
      - name: Deploy to Internet Computer
        run: |
          # Store identity in a temporary file
          echo "${{ secrets.IC_IDENTITY_PEM }}" > identity.pem
          chmod 600 identity.pem
          
          # Run deployment script
          ./scripts/deploy_ic.sh identity.pem
          
          # Clean up
          rm identity.pem