name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test1:
    uses: ./.github/workflows/test1.yml
    needs: build

  test2:
    uses: ./.github/workflows/test2.yml
    needs: build

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [test1, test2]
